class ShoppingCart:  
    def __init__(self):  
        self.cart = []  
  
    def add_item(self, item_name, price, quantity):  
        item = {  
            'name': item_name,  
            'price': price,  
            'quantity': quantity  
        }  
        self.cart.append(item)  
  
    def view_cart(self):  
        if not self.cart:  
            print("购物车是空的。")  
        else:  
            print("购物车中的商品:")  
            for item in self.cart:  
                print(f"商品: {item['name']}, 单价: {item['price']}元, 数量: {item['quantity']}")  
  
    def total_price(self):  
        total = sum(item['price'] * item['quantity'] for item in self.cart)  
        return total  
  
def main():  
    cart = ShoppingCart()  
  
    while True:  
        print("\n1. 添加商品到购物车")  
        print("2. 查看购物车")  
        print("3. 结账")  
        print("4. 退出")  
  
        choice = input("请选择操作: ")  
  
        if choice == '1':  
            item_name = input("请输入商品名称: ")  
            price = float(input("请输入商品价格: "))  
            quantity = int(input("请输入商品数量: "))  
            cart.add_item(item_name, price, quantity)  
        elif choice == '2':  
            cart.view_cart()  
        elif choice == '3':  
            total = cart.total_price()  
            print(f"\n总价: {total}元")  
        elif choice == '4':  
            print("再见!")  
            break  
        else:  
            print("无效的选择，请重新选择。")  
  
if __name__ == "__main__":  
    main()
